using OpenQA.Selenium;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Text;
using System.Threading;

namespace TestProject1.Pages
{
    class AssessmentAdminPage : DriverHelper
    {
      
        public IWebElement AssessmentComponent => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[2]/div[2]/div/div/ul/li[6]/a"));
        public IWebElement AssessmentSet => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[2]/div[2]/div/div/ul/li[6]/ul/li[1]/a"));
        public IWebElement NewAssessment => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/app-assessmentset/content-loader/div/div[1]/div/permission-block/button"));
        public IWebElement aTitle => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[1]/synapze-cx-form-control/div/span[1]"));
        public IWebElement aEffectiveDate => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[3]/div/div[1]/synapze-cx-form-control/synapze-cx-calendar/form/p-calendar/span/input"));
        public IWebElement aSelectEffectiveDate => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[3]/div/div[1]/synapze-cx-form-control/synapze-cx-calendar/form/p-calendar/span/div/div[2]/button[1]/span"));
        public IWebElement ContainerAssessment => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div"));
        public IWebElement dropdownAT => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[1]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement Test => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[1]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement Trivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[1]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li"));
        public IWebElement Survey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[1]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[3]/li"));
        
        //----------------------------------------------------Test--------------------------------------------------------------------------------
        
        public IWebElement MaxAttempts => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement SelectMaxAttempts => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement PassingScore => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[3]/synapze-cx-form-control/div/p-inputnumber/span/input"));
        public IWebElement TestDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[1]/synapze-cx-form-control/p-spinner/span/input"));
        public IWebElement dropdownTestDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public By SelectTestDuration => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li");
        public ReadOnlyCollection<IWebElement> Feedbackafter => Driver.FindElements(By.CssSelector("[type='checkbox']"));
        public IWebElement HintFeedBack => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[7]/div/div/div"));
        public IWebElement btnAddTest => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[11]/permission-block/button"));

        //------------------------------------------------Trivia--------------------------------------------------
        public IWebElement AssessmentTriviaType => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
       
        //------RapidFire----

        public IWebElement RapidFire => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement MaxAttemptsTrivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[3]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement SelectMaxAttemptsTrivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[3]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement PassingScoreTrivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[4]/synapze-cx-form-control/div/p-inputnumber/span/input"));
        public IWebElement TriviaDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[2]/synapze-cx-form-control/p-spinner/span/input"));
        public IWebElement dropdownTriviaDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[3]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement SelectTriviaDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[3]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement TimerTrivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div/div/label"));
        public IWebElement btnAddTrivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[10]/permission-block/button"));
        
        //------SkillBuilder----

        public IWebElement SkillBuilder => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li"));
        public IWebElement CompetencyType => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[3]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement SelectCompetencyType => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[3]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement SkillsType => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[4]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement SelecytSkillsType => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[4]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement MaxAttemptsSB => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[5]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement SelectMaxAttemptsSB => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[5]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement PassingScoreSB => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[6]/synapze-cx-form-control/div/p-inputnumber/span/input"));
        
        //------Featured----

        public IWebElement Featured => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[4]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[3]/li"));
        public IWebElement DropdownCategory => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[6]/synapze-cx-form-control/tenant-only-category-selector/div/form/div/div/div/div[1]/tenant-category-selector-dropdown/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement ChooseCategory => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[6]/synapze-cx-form-control/tenant-only-category-selector/div/form/div/div/div/div[1]/tenant-category-selector-dropdown/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement btnAddCategory => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[6]/synapze-cx-form-control/tenant-only-category-selector/div/form/div/div/div/div[2]/button"));

        //-----------------------------------------Survey--------------------------------------------------
       
        public IWebElement SurveyDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[1]/synapze-cx-form-control/p-spinner/span/input"));
        public IWebElement dropdownSurveyDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public IWebElement SelectSurveyDuration => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[5]/div/div[2]/synapze-cx-form-control/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li"));
        public IWebElement btnAddSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[9]/permission-block/button"));
        
        //---------------------------------------Complete Test Form------------------------------------
        public IWebElement TitleTest => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[1]/synapze-cx-form-control/div"));
        public IWebElement DescriptionTest => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[2]/synapze-cx-form-control/textarea"));
        public IWebElement DropdownLanguageTest => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-locale-selector/form/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public By SelectLanguageTest => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-locale-selector/form/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li");
        public IWebElement SearchLocation => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[1]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public By opcLocation => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[1]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li");
        public By opcRegion => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[1]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[3]/li");
        public IWebElement SelectLocation => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public By opcAtlantic => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li");
        public By opcFordCanada => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li");
        public By opcWestern => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li");
        public By opcPacific => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li");
        public IWebElement btnAddLocationTest => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[6]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[3]/button"));
        public IWebElement addQuestions => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[7]/div[1]/div/div[1]/synapze-cx-form-control/input"));
        public IWebElement btnAddCompetencies => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[7]/div[2]/div[1]/button"));
        public IWebElement selectCompetencies => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[7]/div[2]/div[1]/ul/li[1]"));
        public IWebElement addCompetencies => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[7]/div[2]/div[1]/ul/li[3]/button"));
        public IWebElement btnAddSkills => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[7]/div[2]/div[3]/button"));
        public IWebElement addSkills => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[7]/div[2]/div[3]/ul/li[1]/button"));
        public IWebElement addNumberSkills => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[7]/div[2]/div[4]/div/skill-count-selector/div/div[2]/div/div[1]/div/span[2]/button"));
        public IWebElement btnSelectQuestions => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[11]/button"));
        public IWebElement selectQuestions => Driver.FindElement(By.XPath("/html/body/modal-container/div/div/div[2]/div/question-search-grid/content-loader/div/synapze-cx-grid/div/div/div[1]/label/assessment-question/div"));
        public IWebElement btnSaveQuestions => Driver.FindElement(By.XPath("/html/body/modal-container/div/div/div[3]/div/button"));
        public IWebElement btnSelectCertificate => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[13]/button"));
        public IWebElement SelectCertificate => Driver.FindElement(By.XPath("/html/body/modal-container/div/div/div[2]/div/div/div/div[1]/div"));
        public IWebElement btnSaveCertificate => Driver.FindElement(By.XPath("/html/body/modal-container/div/div/div[3]/div/button[2]"));
        public IWebElement btnSaveTest => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[15]/div[2]/div/div[2]/button"));
        public IWebElement btnSaveAssessment => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[12]/div/div[2]/permission-block/button"));
        public IWebElement btnAcceptSaveAssessment => Driver.FindElement(By.XPath("/html/body/div[3]/div/div[3]/button[1]"));
        public IWebElement btnPublishAssessment => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[12]/div/div[4]/permission-block/button"));

        //-----------------------------Complete form Survey-----------------------------

        public IWebElement DropdownLanguageSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[4]/synapze-cx-form-control/tenant-locale-selector/form/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public By SelectLanguageSurvey => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[4]/synapze-cx-form-control/tenant-locale-selector/form/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li");
        public IWebElement SearchLocationSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[1]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public By opcLocationSurvey => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[1]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li");
        public By opcRegionSurvey => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[1]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[3]/li");
        public IWebElement SelectLocationSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[3]"));
        public By opcAtlanticSurvey => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li");
        public By opcFordCanadaSurvey => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li");
        public By opcWesternSurvey => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[1]/li");
        public By opcPacificSurvey => By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[2]/synapze-cx-simple-dropdown/form/p-dropdown/div/div[4]/div/ul/p-dropdownitem[2]/li");
        public IWebElement btnAddLocationSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[5]/synapze-cx-form-control/tenant-location-selector/content-loader/div/form/div[1]/div/div[3]/button"));
        public IWebElement btnSelectQuestionsSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[8]/button"));
        public IWebElement btnSaveSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[10]/div[2]/div/div[2]/button"));
        public IWebElement btnSaveAssessmentSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[10]/div/div[2]/permission-block/button"));
        public IWebElement btnPublishAssessmentSurvey => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[10]/div/div[4]/permission-block/button"));

        //----------------Complete form Trivia ------------------------------
        public IWebElement btnSaveTrivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[2]/div/add-edit-assessment/content-loader/div/form/div[13]/div[2]/div/div[2]/button"));
        public ReadOnlyCollection<IWebElement> AcceptSave => Driver.FindElements(By.CssSelector("[type='button']"));
        //--------------- Show Assessment --------------------------
        public IWebElement SearchAssessment => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/app-assessmentset/content-loader/div/div[2]/div/div/assessmentset-search/content-loader/div/form[1]/div/div[2]/input"));
        public IWebElement btnSearchAssessment => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/app-assessmentset/content-loader/div/div[2]/div/div/assessmentset-search/content-loader/div/form[1]/div/div[2]/button[1]"));
        public IWebElement CheckAssessment => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/app-assessmentset/content-loader/div/div[2]/div/div/synapze-cx-grid/div/table/tbody/tr/td[1]/div/a"));

        public IWebElement btnSaveAssessmentTrivia => Driver.FindElement(By.XPath("/html/body/app-root/app-admin-layout/div/section[1]/div/edit-assessment-sets-view/content-loader/div/div/edit-assessment-set/content-loader/div/div[1]/div/form/div[11]/div/div[4]/permission-block/button"));
        public void SelectDropdown(IWebElement Dropdown, By Option)
        {
            Dropdown.Click();
            IWebElement OptionLocation = Driver.FindElement(Option);
            OptionLocation.Click(); 
        }
        public void ButtonLocations(int type)
        {
            if (type == 1) { btnAddLocationTest.Click(); }
            else if (type == 2) { btnAddLocationSurvey.Click(); }
        }

        public void SelectFeedBackAfter(int opc)
        {
            IJavaScriptExecutor executor = (IJavaScriptExecutor)Driver;
            executor.ExecuteScript("arguments[0].click();", Feedbackafter[opc]);
        }
        public void AcceptSaveAssessment(int save)
        {
            IJavaScriptExecutor executor = (IJavaScriptExecutor)Driver;
            executor.ExecuteScript("arguments[0].click();", AcceptSave[save]);
        }

    }
}
